// Writes src/version.ts from package.json's version field. Run by `build`,
// `prepublishOnly`, and the root `version` script so the constant can never
// drift from the manifest. CI re-runs it and fails on `git diff --exit-code`.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const pkgDir = join(dirname(fileURLToPath(import.meta.url)), '..')
const { version } = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8'))

const contents = `// Generated by scripts/sync-version.mjs — do not edit by hand.
export const VERSION = '${version}'
`

writeFileSync(join(pkgDir, 'src', 'version.ts'), contents)
